{% set name = "types-emoji" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-emoji-{{ version }}.tar.gz
  sha256: 33a7f5cd37c522c2e59347fe7e81e392b5be56fa8dc3493fae5c0f75b691211f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/emoji-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for emoji
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
