{% set name = "types-emoji" %}
{% set version = "1.7.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-emoji-{{ version }}.tar.gz
  sha256: 1e1341399ed1dd10a54d348ec7bb0708a56cd04f79702941fef5db60d276ea46

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/emoji-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for emoji
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
